### ISSUE TITLE
has, exists & dojorc

### ISSUE THREAD

**Issue by denov** [dojo/framework#100]
**Enhancement** 

`has` and `exists` seem to not be consistent in usage.  `has` looks for features set either in `dojorc` or from the cli-build-app `-f` flag.  where `exists` only pays attention to features set by `add`

right now there doesn't seem to be a way to check if a feature was set via `dojorc` or `-f`.   `has` throws an error if not set and exists always returns false.
 

Package Version: 3.0.0

**Expected behavior:**

i would expect `exists` to see features set by any method - `add`, `dojorc`, or `-f`

**Comment by matt-gadd** [comment]
@denov thanks for raising the issue, i've raised a more specific issue in webpack-contrib if you'd like to track (https://github.com/dojo/webpack-contrib/issues/68).
