### ISSUE TITLE
w(Link) does not work with query parameter

### ISSUE THREAD

**Issue by ILoveITScience** [dojo/framework#114]
I have the following code:

```
import { Link as A } from '@dojo/framework/routing/Link';
...

path: 'module/{modulename}?{filter}&{filter2}',
    outlet: 'module',
    defaultParams: {
        filter: 'default',
        filter2: 'default2'
    },
```
but the w(Link ...) widgets do not work with this configuration (they are not clickable). I tried several combinations like:

```
w(A, { to: `${link}`, params: { modulename: parameter }, queryParams: { filter:"asdf", filter2:"adsf" }, classes: [] }, [...

w(A, { to: `${link}`, params: { modulename: parameter }, classes: [] }, [...
```

but they all did not work.

DoJo Version:
    "@dojo/framework": "^3.0.1",
    "@dojo/webpack-contrib": "^3.0.3",
    "@dojo/widgets": "^3.0.0",

@agubler here is the issue as you requested

**Comment by ILoveITScience** [comment]
@agubler  in which DoJo version will the fix be available?

**Comment by agubler** [comment]
@iloveitscience these changes will be 4.0.0 in the meantime you can use `$` as the delimiter in the config as work around.

We can’t really back port the changes as technically they are breaking.

**Comment by ILoveITScience** [comment]
the workaround works
thank you
