### ISSUE TITLE
doc are obsolet: @afterRender() -> runAfterRenders

### ISSUE THREAD

**Issue by ILoveITScience** [dojo/framework#119]
https://dojo.io/docs/index.html#doc--dojo__framework__v3_0_0__src__widget-core__README_md--afterrender--afterrender

I would like to execute some code after the render method. According to the documentation there is a @afterRender() annotation. But it’s not available. Instead I found the runAfterRenders(DNode) method. Is the documentation obsolete?

DoJo Version:
"@dojo/framework": "^3.0.1",
"@dojo/webpack-contrib": "^3.0.3",
"@dojo/widgets": "^3.0.0",

**Comment by agubler** [comment]
Closing as I believe the documentation is correct. Please re-open if I have missed something.
