### ISSUE TITLE
Write a blog announcing @dojo/framework

### ISSUE THREAD

**Issue by devpaul** [dojo/framework#16]
Write a dojo.io blog outlining the changes we're making and justifying the move to @dojo/framework

**Comment by devpaul** [comment]
WIP here: https://github.com/devpaul/dojo.io/blob/dojo-framework/site/source/_drafts/dojo-framework.md

I haven't submitted this as a PR yet. We'll make the call on the Monday meeting whether this blog should go out to announce Dojo 3 or prior to explain the work we're doing.

**Comment by sebilasse** [comment]
@devpaul It would also be nice to know if we should open issues in one of the seven packages (as I just did ;) or in this one.

**Comment by devpaul** [comment]
This depends on #13 providing a clear set of instructions for updating so we can add it to the blog
