### ISSUE TITLE
defaultRoute=true is not working in Dojo4 in case of StateHistory

### ISSUE THREAD

**Issue by bipindigits** [dojo/framework#195]
**Bug / Enhancement** 

**defaultRoute=true** attribute is not working in Dojo4 in case of **StateHistory**.Please see the code sandbox for this issue.
Link - https://codesandbox.io/s/oo014r8v8q

Package Version: Dojo 4.0.0

**Code**

import { StateHistory } from '@dojo/framework/routing/history/StateHistory';

const routingConfig = [
	{
		path: 'home',
		outlet: 'home',
		**defaultRoute: true**
	},
	{
		path: 'form',
		outlet: 'form'
	}
];

const registry = new Registry();
start();
registerRouterInjector(routingConfig, registry, {
	HistoryManager: StateHistory
});

const r = renderer(() => w(App, {}));
r.mount({ registry });

**Expected behavior:**

![image](https://user-images.githubusercontent.com/34906530/49363022-8e0ed000-f706-11e8-826f-662a4c6f2c9d.png)

**Actual behavior:**

![image](https://user-images.githubusercontent.com/34906530/49363524-e2667f80-f707-11e8-9629-41cc3882fbcf.png)

**Comment by agubler** [comment]
This has been back ported and released in 4.0.3
