### ISSUE TITLE
Initialization section on Web Components is unclear

### ISSUE THREAD

**Issue by jcfranco** [dojo/framework#208]
[This section](https://github.com/dojo/framework/blob/5ce5f24f268064239041381047da6be112481d5d/src/widget-core/README.md#initialization) shows an `initialization` method being used in the context of web components, but it's not clear where this method comes into play. 

There doesn't seem to be any relevant code in the repo (I originally thought it was a lifecycle hook), so 
I'm guessing this is some sort of parent/app-level method. If so, maybe adding more details to the example snippet can help?

Happy holidays, BTW! 🎄

**Comment by agubler** [comment]
Happy New Year! @jcfranco - The `initialization` section in the readme is actually out of date as the functionality was removed a while back. I'll update the README to ensure it is up to date and close this issue once it has been.

Thank you for raising the issue 😄
