### ISSUE TITLE
Styling web component wrapper node

### ISSUE THREAD

**Issue by jcfranco** [dojo/framework#209]
Is there a recommended approach to style the root of a web component? Custom web components have a wrapper node and I couldn't find anything on it in the README nor the tutorials. 

The went with following in the meantime:

**`foo-bar/index.m.css`**
```css
/* custom element selector */
foo-bar { /* ... */ }

/* theme */
.root { /* ... */ }

/* fixed */
.rootFixed { /* ... */ }
```

I figured that adding a custom element selector would be fine since registered custom element names are expected to be unique anyways. Please let me know if there's a better way to do this.

**Comment by agubler** [comment]
@jcfranco My first question would be why would you need to style the placeholder node of the custom element? Once the CE is hydrated and rendered, then it is appended to the placeholder node so styling the root of the widget should be all that is needed.

**Comment by matt-gadd** [comment]
Hey @jcfranco, yeah this is currently an issue for our custom element output as custom elements default to `display: inline`, which is not always desirable. This has been discussed a few times over at w3c (https://github.com/w3c/webcomponents/issues/224, https://github.com/w3c/webcomponents/issues/426, https://github.com/w3c/webcomponents/issues/468). In the Custom Element Showcase we end up adding a class to the elements to control this: https://dojo.github.io/examples/custom-element-showcase/

As a proposal for v5, I think an additional option per element for `@dojo/cli-build-widget` to define an element as `inline` or `inline-block` makes sense. In the custom element handler we can then add the appropriate style for you. This could then still be overridden by a user with `!important` if needed.

In the mean time using the element selector like you put in your original issue seems reasonable 👍

**Comment by jcfranco** [comment]
@matt-gadd Thanks for the info, I was not aware of the ongoing discussion. 😄

Adding a build option per element sounds good. 

Closing since my proposed workaround seems fine and v5 would simplify this process.
