### ISSUE TITLE
Web component attribute values + widget property types

### ISSUE THREAD

**Issue by jcfranco** [dojo/framework#210]
Before my issue, I'd like to say Happy New Year!  🎉🍾🎆 I hope everyone had a wonderful holiday season. 😄 

---

Say I have the following widget:

```ts
export interface FooBarProperties extends WidgetProperties {
  amount: number;
  flag: boolean;
  text: string;
}

@customElement({
  tag: "foo-bar",
  attributes: ["amount", "flag", "text"]
})
export class FooBar<P extends FooBarProperties = FooBarProperties> extends WidgetBase<P> {
  render() {
    const { amount, flag, text } = this.properties;
    // ...
  }
}
```

Any widget properties that are exposed as web component attributes will receive string values, so there will be a mismatch between non-string interface properties and the runtime values. What would be the recommended way of dealing with this? 

Use the `beforeProperties` hook to ensure type? 

```ts
export class FooBar<P extends FooBarProperties = FooBarProperties> extends WidgetBase<P> {
  @beforeProperties()
  protected myBeforeProperties(properties: FooBarProperties): FooBarProperties {
    // ensure types for `amount` & `flag`
  }

  render() {
    const { amount, flag, text } = this.properties;
    // ...
  }
}
```

Union string types to non-string properties and ensure type within render? 

```ts
export interface FooBarProperties extends WidgetProperties {
  amount: number | string;
  flag: boolean | string;
  text: string;
}

export class FooBar<P extends FooBarProperties = FooBarProperties> extends WidgetBase<P> {
  render() {
    const { amount, flag, text } = this.properties;
    // ensure types for `amount` & `flag`
    // ...
  }
}
```

Something else?

**Comment by matt-gadd** [comment]
At the moment we only recommend specifying `attributes` that are types of `string` on the widget properties, and other types just being `properties`. If you do wish to support a non-string type, the second solution is preferable over a lifecycle hook and we have done that once in widgets: https://github.com/dojo/widgets/pull/601/files#diff-2c66eee7a9b3f6734b1a91bdf543a991R37). 

In the future we plan to do these attribute/property conversions for you via introspecting the properties interface at build time, some preliminary work has been done here: https://github.com/dojo/webpack-contrib/pull/98

**Comment by jcfranco** [comment]
Awesome! Thanks for the info.
