### ISSUE TITLE
Update shim/global.ts to use `globalThis`

### ISSUE THREAD

**Issue by dasa** [dojo/framework#222]
**Bug** 

Package Version: 5 

**Code**

Chrome, Safari TP and TS are using `globalThis` rather than `global`. See: https://github.com/Microsoft/TypeScript/pull/29332 (This PR makes it sound like TS will handle this in the future such that the shim would no longer be needed.)

**Expected behavior:**

**Actual behavior:**

**Comment by dasa** [comment]
See: https://mathiasbynens.be/notes/globalthis

**Comment by maier49** [comment]
Resolved by #437
