### ISSUE TITLE
Moving widget-core to core

### ISSUE THREAD

**Issue by matt-gadd** [dojo/framework#280]
**Enhancement**

When we started working on `widget-core`, we wanted to call it `core` but unfortunately `core` already existed as a lot of modules transferred over from the initial `dojo` to `dojo2` transition. Given since then we have effectively removed all those legacy things and we have a total 4 utility modules left in `core`, it's difficult to see why this would exist anymore on it's own. In which case we could move those 4 utility modules over to `widget-core`, and rename `widget-core` to `core`

**Comment by tomdye** [comment]
Sounds like a good idea to me.

**Comment by agubler** [comment]
Given that it should be a trivial migration for `cli-upgrade-app` and `framework/widget-core` being the true core suite of the framework modules, this makes sense to me.

**Comment by agubler** [comment]
Closed by #357
