### ISSUE TITLE
AssertionTemplate does not strip `assertion-key` from properties

### ISSUE THREAD

**Issue by grayrest** [dojo/framework#293]
**Bug/Enhancement**

When using higher order components with assertion templates, the DNodes in the HoC properties aren't stripped of their `assertion-key`s

Package Version: 5.0.2

**Code**

```
const baseTemplate = assertionTemplate(() => (
  <HigherOrder
     assertion-key="works-fine"
     componentProperty={<div assertion-key="not-removed">hi</div>}
  />
);
```

**Comment by matt-gadd** [comment]
So having thought hard about this I don't think we should change the behaviour. The rationale being that assertion templates and the selector itself works on a tree of nodes (just like in the real dom with querySelector), which properties are not. I think If we start recursing into properties i'm not sure where it'd end (ie should we iterate objects that then have DNodes in them?). 

It's pretty trivial to do the above with composing assertion templates I think (which would be the same pattern for render functions as properties too) for example:

```typescript
const componentPropertyTemplate = assertionTemplate(() => (
  <div assertion-key="bar">Bar</div>
));

const fooTemplate = assertionTemplate(() => (
  <Foo assertion-key="foo" componentProperty={} />
)).setProperty("@foo", "componentProperty", componentPropertyTemplate())
```
