### ISSUE TITLE
Test harness should throw on missing selectors

### ISSUE THREAD

**Issue by aciccarello** [dojo/framework#318]
**Enhancement** 
The testing harness should throw when the selector isn't found. Th.is would help debug failing tests

Package Version: 

**Code**
```typescript
h.trigger('@nonExistantSelector', 'whatToTrigger');
```

**Expected behavior:**
The trigger call will throw an error indicating the selector could not be found.

**Actual behavior:**
The trigger passes silently.

**Comment by ferni1988** [comment]
Stop

**Comment by aciccarello** [comment]
@ferni1988 GitHub doesn't support unsubscribing that way (it replies to the issue). You will have to login to GitHub to manage your email preferences or un-watch a repository.
