### ISSUE TITLE
Reference guide: Building Dojo Applications

### ISSUE THREAD

**Issue by vansimke** [dojo/framework#322]
Covering all aspects of how to build Dojo applications. Merging, updating & streamlining content from:
* Quickly scaffolding new applications: https://github.com/dojo/cli-create-app/blob/master/README.md
* Building applications + difference between dev and production builds: https://github.com/dojo/cli-build-app/blob/master/README.md
* Using bundles - benefits around resource reduction + automatic deferred loading; how to define them; how cross-bundle duplication may occur for shared resources across multiple bundles
* Creating PWAs
* Using BTR within an application
* Using has() for build time elision of ununsed features - https://github.com/dojo/framework/blob/master/src/has/README.md
* Other relevant aspects (dojorc not covered in any of the above; ejection) from https://github.com/dojo/dojo.io/blob/master/site/source/tutorials/006_deploying_to_production/index.md

Info about "locales" and "cldrPaths" can just link to the i18n guide.

**Comment by devpaul** [comment]
WIP here https://github.com/devpaul/framework/tree/build-reference/docs/en/building

Introduction and Basic Usage complete. Some supplemental material to go.
