### ISSUE TITLE
Reference guide: Dojo Stores

### ISSUE THREAD

**Issue by vansimke** [dojo/framework#324]
* Describing advanced state management for Dojo apps (basic + intermediate are being covered in 'creating widgets').
* Covering how to use stores; update & streamline content from: https://github.com/dojo/framework/blob/master/src/stores/README.md
* Best practices on data model lifecycle (CRUD, handling changes to multiple objects as atomically as possible) & how each step best translates to Processes
* Handling errors, rolling back
* Pointers for integrating with underlying data stores eg REST services?
* NOTE: likely impacted by the new Resources API in v6/v7 so we need to discuss how to approach this guide.

**Comment by agubler** [comment]
Some thoughts on the topics that we should look to cover as part of the stores reference guide, in no particular order:

* Basic Usage Section
  * Basic example of setting up and using a store
  * Process, Commands and Operations overview
  * Connecting store state to application widgets
* StoreProvider
  * Using the StoreProvider
  * StoreProvider API
  * Registering paths for invalidation etc
* Working with Commands
  * Type safe commands with the command factory
  * The Command Request API
* Asynchronous and Concurrent Commands
* Process Middleware
* Immutable patterns when updating state
* Optimistic Update Pattern
* Handling errors and rollback
* Composing Commands
* Working with Arrays
* Transforming Process Payloads
* Normalizing State
* Custom State Management Implementation (i.e. immutable)
* Working with external / remote data sources
* Dojo provided middleware (i.e. local storage, history etc)

**Comment by devpaul** [comment]
WIP: https://github.com/devpaul/framework/tree/stores-reference

**Comment by agubler** [comment]
This has been completed by https://github.com/dojo/framework/pull/453
