### ISSUE TITLE
Reference guide: Dojo's Widget Suite

### ISSUE THREAD

**Issue by vansimke** [dojo/framework#325]
Need to figure out what we want to do for this - all we really have at the moment is https://github.com/dojo/widgets/blob/master/README.md.
* Parts need to be hand-authored (introduction, high-level overview of all widgets), but others are best auto-generated to ensure accuracy over time (theme classes, events)

**Comment by tomdye** [comment]
This can be closed now that we have parade.

**Comment by agubler** [comment]
A link to the widget documentation site https://widgets.dojo.io/
