### ISSUE TITLE
Returning undefined from the create factory results in being incorrectly inferred as middleware

### ISSUE THREAD

**Issue by matt-gadd** [dojo/framework#454]
**Bug**

**Code**
```tsx
const factory = create();
const Widget = factory(() => {
  return undefined;
});
```

**Expected behavior:**

To be inferred as a widget over a middleware.

**Actual behavior:**

It is inferred as a middleware.

**Comment by agubler** [comment]
This only seems to be an issue on codesandbox as they use a pre 3.4.5 release of TypeScript.
