### ISSUE TITLE
TypeError: The TouchEvent.changedTouches getter can only be used on instances of TouchEvent(anonymous function) @ dojo.js:formatted:8343

### ISSUE THREAD

**Issue by sra-coder** [dojo/framework#456]
Hi, I am getting above error one of my application, while scrolling in browser emulator(browserstack). can you please help me out.

![image](https://user-images.githubusercontent.com/52801369/61586735-17b1c780-ab49-11e9-98c2-8d117451a7be.png)

**Bug / Enhancement** 

Package Version: 

**Code**

**Expected behavior:**

**Actual behavior:**

**Comment by matt-gadd** [comment]
@sra-coder hi, I don’t think this is related to dojo/framework, but rather the old dojo toolkit which is at http://github.com/dojo/dojo
