### ISSUE TITLE
Some content was outdated In testing/supplemental.md

### ISSUE THREAD

**Issue by xiaohulu** [dojo/framework#464]
**Enhancement** 

Package Version: v6.0.0-alpha.14

**Code 1**

In https://github.com/dojo/framework/blob/master/docs/en/testing/supplemental.md  **Line 101**

> The harness also supports tsx usage as show below. **For the rest of the README the examples will be using the programmatic w() API**, there are more examples of tsx in the unit tests.

"For the rest of the README the examples will be using the programmatic w() API" was outdated.

1. There is no README file;
1. rest of examples all use `tsx`

**Code 2**

In https://github.com/dojo/framework/blob/master/docs/en/testing/supplemental.md  **Line 348**

```ts
const h = harness(() => <MyWidget {...properties} />, {
    middleware: [store, mockStore]
});
```
`middleware` should be an array of tuple?

```ts
const h = harness(() => <MyWidget {...properties} />, {
    middleware: [[store, mockStore]]
});
```

**Code 3**

In https://github.com/dojo/framework/blob/master/docs/en/testing/supplemental.md  **Line 612**

The code in Line 612-615 should be removed

```ts
describe('Profile', () => {
	it('default renders correctly', () => {
		const h = harness(() => w(Profile, {}));
		h.expect(profileAssertion);
	});
});
612  it('default renders correctly', () => {
613      const h = harness(() => w(Profile, {}));
614      h.expect(profileAssertion);
615 });
```

**Code 4**

In https://github.com/dojo/framework/blob/master/docs/en/testing/supplemental.md  **Line 637**

1. `~message` should be `~welcome`
2. `the number 5` should be `Welcome Kel Varnsen!`

**Code 5**

In https://github.com/dojo/framework/blob/master/docs/en/testing/supplemental.md  **Line 695**

```ts
const h = harness(() => w(Home, { fetchItems }));
```

should be

```ts
const h = harness(() => w(Action, { fetchItems }));
```

**Comment by agubler** [comment]
@xiaohulu Thanks, I have raised #466 that addresses these issues.
