### ISSUE TITLE
[Projector#merge] Existing CSS classes are not preserved when topmost render toggles rendering

### ISSUE THREAD

**Issue by agubler** [dojo/framework#47]
@jcfranco commented on [Mon May 07 2018](https://github.com/dojo/widget-core/issues/923)

**Bug**

When using `Projector#merge`, if the topmost `render` toggles rendering (returns valid VDOM or undefined between renders), existing CSS classes are not preserved on subsequent renders:

Package Version: 2.0.0

**Code**

```html
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Preserve CSS classes when merging</title>
</head>
<body>
	<div id="target" class="preserve-me" />
</body>
</html>
```

```ts
import { ProjectorMixin } from '@dojo/widget-core/mixins/Projector';
import App from './widgets/App';

let visible = true;
const Projector = ProjectorMixin(App);
const projector = new Projector();
projector.setProperties({ visible });
projector.merge(document.getElementById('target')!);

setInterval(() => {
	visible = !visible;
	projector.setProperties({ visible });
}, 1000);
```

```ts
export default class App extends WidgetBase<AppProperties> {
	protected render() {
		const { visible } = this.properties;

		return visible ?
				v('div', { classes: css.app }, [
					v('div', [
						'hello'
					])
				]) :
				null;
	}
}
```

[Demo](https://jcfranco.github.io/dojo-2-test-cases/merge-not-preserving-original-classes/output/dist/)

**Expected behavior:**

`preserve-me` class is preserved whenever the app is rendered.

**Actual behavior:**

`preserve-me` class is dropped when the app is re-rendered (1st render is 👌).

**Comment by matt-gadd** [comment]
I'm going to close this issue as working as designed. A `projector.merge()` does not guarantee the state of the initial dom is carried over across renders, and really the merge should only ever be used when the dom exactly mirrors that render (ie a server side or build time render of the same thing).
