### ISSUE TITLE
The Drag Meta does not work in Safari 12.1.2

### ISSUE THREAD

**Issue by edwardstumpf** [dojo/framework#481]
**Bug**

Package Version: 5.0.4 (and 3.0.1)

The Drag Meta does not work in the current release of Safari (12.1.2).

I noticed this after refactoring my application to no longer use a Custom Element.  During Safari testing, we discovered that any widget within the app that used the Drag Meta was now broken.

I believe this is because the [Drag Meta relies on Pointer events](https://github.com/dojo/framework/blob/b8e0228c4025cb803d1c56521b054f6d5e6dfdb2/src/core/meta/Drag.ts#L231-L234), which are [not currently supported in Safari](https://caniuse.com/#feat=pointer).  After including a polyfill like [handjs](https://www.npmjs.com/package/handjs), the Drag Meta was able to function and the impacted widgets resumed working as expected.

I'm not sure why using a Custom Element allowed the Drag Meta to work in Safari.

**Code**

Here is a basic app for testing the Drag meta (borrowed and upgraded from another issue): https://codesandbox.io/embed/dojo-codesandbox-template-t144i

**Expected behavior:**

When you click and drag the words 'Drag me!', the "Is Dragging?" value will change to true and the "Delta" value will update.

**Actual behavior in Safari 12.1.2:**

When you click and drag the words 'Drag me!', the "Is Dragging?" value remains false and the "Delta" value doesn't change.

**Comment by matt-gadd** [comment]
Hi @edwardstumpf. We include the pepjs polyfill from https://github.com/jquery/PEP automatically as part of @dojo/cli-build-app (https://github.com/dojo/cli-build-app#polyfills) . If you're not using the build tool you should load https://github.com/dojo/framework/blob/6d4b4a8d2324252b635fe0a1efa6f685c44d1bc3/src/shim/browser.ts manually before loading your application. 

Hope that answers your question. We'll try and update the documentation to make this more clear.

**Comment by edwardstumpf** [comment]
After analyzing my application's code, the line "import '@dojo/framework/shim/browser';" was included in the original code but not in post-refactor code.  Thank you for pointing this out.  This resolves my issue.
