### ISSUE TITLE
Wrong code example for router query params

### ISSUE THREAD

**Issue by CatalinNarita** [dojo/framework#511]
**Bug** 

The revamped documentation has a wrong example regarding dojo router's query params.

Package Version: 6.0.0

**Expected behavior:**

An example illustrating dojo router's query params should be present

**Actual behavior:**

The actual example does not illustrate the functionality

`export default [
    {
        path: 'home/{page}',
        outlet: 'home'
    }
];`

**Comment by agubler** [comment]
This has been corrected.
