### ISSUE TITLE
Dojo 7

### ISSUE THREAD

**Issue by agubler** [dojo/framework#530]
## Dojo 7 Plan

Epic for all the planned/desired enhancements and discussions for the next major Dojo release (Dojo 7). The items with associated issues are 100% planned, other items maybe be introduced or bumped into the next release depending on time.

**Note: Issue creation in progress across these**

### Large

* [Dojo Data](https://github.com/dojo/framework/issues/524)
* [Dojo Templating](https://github.com/dojo/framework/issues/525)
* [Rewrite Test Harness ](https://github.com/dojo/framework/issues/535)
* Dojo Server Side Rendering
* Dojo Unit Test Command
* Dojo Dashboard
* Dojo Blocks (pre-built blocks)
* Modern Dojo Toolkit
* Dojo DevTools
* [Testing Playground](https://github.com/dojo/framework/issues/515)

### Small/Medium

* [Support for wildcard routing](https://github.com/dojo/framework/issues/330)
* Statically resolve has.add based on predefined feature set
* Support for using middleware with virtual nodes (investigation)
* [Build time rendering API](https://github.com/dojo/webpack-contrib/issues/134)
* [Routing middleware](https://github.com/dojo/framework/issues/531)
* [Auto code splitting support with routing middleware](https://github.com/dojo/framework/issues/531)
* [Jsdom support for BTR](https://github.com/dojo/webpack-contrib/issues/197)
* [BTR pages in parallel](https://github.com/dojo/webpack-contrib/issues/184)
* [Enhanced logger for cli-build-app](https://github.com/dojo/cli-build-app/issues/299)
* [“heuristic" static mode for BTR to determine if a page is eligible to be static](https://github.com/dojo/cli-build-app/issues/123)
* Capture user actions performed before hydration is completed on merge
* [Print production warning when using serve with cli-build-app](https://github.com/dojo/cli-build-app/issues/296)
* [Support hash links with `StateHistory`](https://github.com/dojo/framework/issues/281)
* [Slotting for Dojo web components](https://github.com/dojo/framework/issues/255)(discussion/investigation)
* [Named children API](https://github.com/dojo/framework/issues/528)
* [Support extending dojorc files](https://github.com/dojo/cli/issues/295)
* [Drag Middleware](https://github.com/dojo/framework/issues/514)
* [Web Animations middleware](https://github.com/dojo/framework/issues/526)
* [Harness and assertion template support for render properties](https://github.com/dojo/framework/issues/529)
* [Assertion Snapshots](https://github.com/dojo/framework/issues/527)
* [Fix consistency of asset output paths](https://github.com/dojo/cli-build-app/issues/314)

### Content

* Getting started with Dojo content
* Custom elements documentation
* Dojo static site generation

**Comment by rgcl** [comment]
Hi, what "Modern Dojo Toolkit" means?
Any related with the dojotoolkit.org?

**Comment by agubler** [comment]
Hey @rgcl. We are experimenting with a modern distributable of dojo toolkit, but nothing concrete at the moment.

**Comment by agubler** [comment]
Dojo has been released, closing this epic
