### ISSUE TITLE
Loading a deployed application of a different JS-Framework into modern Dojo

### ISSUE THREAD

**Issue by ddraeger82** [dojo/framework#562]
Enhancement

Loading a deployed application of a different JS-Framework into modern Dojo

In a modern Dojo application, we want to integrate the functionality of some small external applications, running on a different server. They can be used standalone, but also provide an API to be used by an embedding application. This external app is written in Dojo1, but it could also be React, Angular or just plain Javascript.

In the example I try to control the external app by its API, but the require-function (by @dojo/loader) is running in an error.
[screenshot](https://github.com/ddraeger82/dojo1-app-resolver/blob/master/dojo1Loader.png)

Code

example here:
-	https://github.com/ddraeger82/dojo1-external (npm install, node app.js)
-	https://github.com/ddraeger82/dojo1-app-resolver (npm install, npm run dev)

Expected behavior:

Application should run, as with Dojo 6

Actual behavior:

**Comment by matt-gadd** [comment]
@ddraeger82 are we okay to close this now or is it still an issue?

**Comment by ddraeger82** [comment]
can be closed - thx for your support
