### ISSUE TITLE
Router's outlet event can not trigger after page load completed when upgrade to dojo 6

### ISSUE THREAD

**Issue by xiaohulu** [dojo/framework#566]
**Bug** 

_Sorry, I can not access [discordapp](https://discordapp.com) for some reason, so I open an issue here._

In dojo 5, I use below code to execute init processes, so if I press F5, then auto emit the outlet event

```ts
router.on('outlet', ({ outlet, action }) => {
	if (action === 'enter') {
```

But after upgrade to dojo 6, outlet event can not emit when I press F5 to refresh page.

I also try `router.start()`, but it not work too.

Package Version: dojo 6 
and  use class-based widget

**Expected behavior:**

When press F5 to refresh a page, can execute the init processes to load data

**Actual behavior:**

When press F5 to refresh a page, router's outlet event not execute after the page load complete.

or where to execute the init processes to load data.

**Comment by agubler** [comment]
@xiaohulu did you pass `autostart: false` with the router options? Doing that should allow you to register any listeners before calling `router.start()`

**Comment by xiaohulu** [comment]
@agubler Thanks! I forget pass `autostart: false`, below code works

```ts
const router = registerRouterInjector(routes, registry, { autostart: false });

router.on('outlet', ({ outlet, action }) => {

});

router.start();
```
