### ISSUE TITLE
icache has no eviction mechanism for individual key/values

### ISSUE THREAD

**Issue by matt-gadd** [dojo/framework#604]
**Enhancement** 

**Code**

```ts
console.log(icache.getOrSet('foo', 'a'));
icache.set('foo', undefined);
console.log(icache.getOrSet('foo', 'b'));
```

**Expected behavior:**
logs:
```ts
a
b
```

**Actual behavior:**
logs:
```ts
a
undefined
```
This is due to there actually being a wrapper around all values in the cache, so `getOrSet` will never be called again, regardless of value.

We should probably define the `undefined` semantics here. Does setting a value to `undefined` mean it's empty and then `getOrSet` should call the `setter` here? Or should we have an explicit `unset` api? or should we have both?

**Comment by agubler** [comment]
@matt-gadd I'm thinking that using `undefined` consistently as the eviction semantics would be sufficient here as you should never need to store undefined explicitly in the cache given it returns undefined when a key is not available. What do you think?

**Comment by agubler** [comment]
After a little discussion, the other option is to add an API to deal with cache eviction. The benefit to this is that we don't have to deal with edge cases like `icache.getOrSet('key', () => new Promise.resolve(undefined));` which could end up causing a render loop. Also it could aligns with the native map APIs that users should be familiar with and it would not be a breaking chance.
