### ISSUE TITLE
Cursor always jump to start when span's contenteditable is true

### ISSUE THREAD

**Issue by xiaohulu** [dojo/framework#625]
**Enhancement** 

Package Version: 6.0.4

**Code**

I define a widget that span's `contenteditable` is true.

```ts
export interface EditableSpanProperties {
    value?: string;
    onChanged: (value)=>void
}

export class EditableSpan extends WidgetBase<EditableSpanProperties> {

    protected render() {
        const { value = "", onChanged } = this.properties;
        return (<span
            key="root"
            oninput=(event: KeyboardEvent) => {const value = event.target.value; onChanged(value);}
            contenteditable="true" >{value}</span>);
    }
}
```

**Expected behavior:**

Then I use `EditableSpan`

```ts
private value = "";

...
<EditableSpan value={value} onChanged={(newValue) => {this.value = newValue; this.invalidator()}}/>
```

When I edit text in span, the cursor should not jump to start. The cursor in editable span should act like the `input` element, not jump to the start.

**Actual behavior:**

When I edit text in span, insert text or delete text, the cursor always jump to start.

**Comment by agubler** [comment]
@xiaohulu Do you think you could provide a codesandbox that demonstrates this behaviour?

**Comment by xiaohulu** [comment]
@agubler Sure! https://codesandbox.io/s/mystifying-allen-dch9y

**Comment by agubler** [comment]
Hello @xiaohulu, sorry for the awfully long delay replying here. There isn't anything that Dojo can do to automatically manage the cursor position, it would need to be something that is done in user land based on the specific requirements of the use case. I put together a very simplistic example using your codesandbox that showed one possible way it could be managed https://codesandbox.io/s/dojo-editable-span-zdyn2. It kind of works but doesn't cover all scenarios (so don't go and use this in production!).
