### ISSUE TITLE
Enhance diffProperty to be able to influence the property values

### ISSUE THREAD

**Issue by agubler** [dojo/framework#643]
**Enhancement**

In middleware there is a need to be able to influence the property values of widgets, for example with the `theme` and `i18n` middleware to ensure that application injected values are made available via the property.

To do this in a typesafe way we could introduce a new API for the diffProperty callback that accepts the properties function as part of the API, using that function we can introspect the property types and the property keys.

**Comment by matt-gadd** [comment]
Fixed in https://github.com/dojo/framework/pull/653
