### ISSUE TITLE
Support for generic parameters on functional widget properties

### ISSUE THREAD

**Issue by jellison** [dojo/framework#679]
**Enhancement**

Class based widgets support generic type arguments for the widget's properties type. For instance:

```tsx
export interface ListProperties<T> {
    data: T[];
}

export class List<T> extends WidgetBase {
}
```

We should investigate adding this support for function-based widgets as well. The `icache` middleware does something similar with `createICacheMiddleware`.

**Comment by agubler** [comment]
For widgets that require a specific type, such as the shape of the data that users is passing, then the same pattern can be followed that we currently use for creating type-safe middleware. This is to create a factory, that can stamp the underlying widget with the type and return the type aware widget to be used in an application.

```tsx
interface GridProperties<S> {
    state: S[]
    fetch: () => S[];
    onRowSelect: (selected: S[]) => void;
}
export function gridFactory<S = any>() {
    const factory = create().properties<GridProperties<S>>();
    return factory(function Grid() {
        // the grid code
    });
}
export default gridFactory();
```

There is a small overhead on users if multiple versions of the same widget need to be used, but the alternative support for generics is unwieldy with function-based widgets.
