### ISSUE TITLE
ActiveLink‘s isActive check should take into account queryParams

### ISSUE THREAD

**Issue by xiaohulu** [dojo/framework#697]
**Enhancement** 

Package Version: 6.0.5

Some url should append common query param `pageid`, for example

```
my/path1?pageid=1
my/path2?pageid=2
```

When outlet path contains queryParam `?{pageid}`, `ActiveLink`'s `activeClasses` not work.

**Code**

https://codesandbox.io/s/staging-violet-e3rib

**Expected behavior:**

If Outlet path contains queryParam `my/path?{queryParam}`, should set background color to red when Link is active.

**Actual behavior:**

not set `activeClasses` when Link is active.

**Comment by agubler** [comment]
@xiaohulu A fix has been raised for this issue, here is a codesandbox that demos the change https://codesandbox.io/s/strange-mclean-io5yy

**Comment by xiaohulu** [comment]
@agubler  Thanks!
