### ISSUE TITLE
Migrate from tslint to eslint

### ISSUE THREAD

**Issue by agubler** [dojo/framework#706]
**Enhancement**

As tslint has been deprecated, we should move to using eslint. 

Depends on a base configuration being added to @dojo/scripts, https://github.com/dojo/scripts/issues/31

**Comment by bitpshr** [comment]
Happy to pick this up.

**Comment by agubler** [comment]
Awesome. I think @nicknisi raised a PR on scripts already that needs reviewing.

**Comment by nicknisi** [comment]
Yes I did! I tested against framework and there are a few issues minor issues in framework that I think should be fixed. I haven’t tested against widgets, though.

**Comment by nicknisi** [comment]
If you want to take this over, that’s totally cool with me, or I can continue.

**Comment by agubler** [comment]
@bitpshr hey, where did you get to with this?
