### ISSUE TITLE
TypeAhead throws with a list of resources

### ISSUE THREAD

**Issue by devpaul** [dojo/framework#740]
**Bug** 

I was working with `TypeAhead` and ran into an issue. When I provide a basic list resource it seems to be treated as a more complex resource. This is the first time I've used the new `TypeAhead` so it could be I'm using it wrong, but according to the types it seems it should work with a list of object with a `value` property.

Package Version: 7.alpha.4

**Code**

https://codesandbox.io/s/dojo-typeahead-q433l?file=/src/App.tsx

```
import { create, tsx } from "@dojo/framework/core/vdom";
import { defaultTransform } from "@dojo/widgets/select";
import TypeAhead from "@dojo/widgets/typeahead";

const factory = create();

const animals = [{ value: "dog" }, { value: "cat" }];

const App = factory(function App() {
  return (
    <TypeAhead
      resource={animals}
      transform={defaultTransform}
      onValue={(value: string) => {
        console.log(value);
      }}
    />
  );
});
```

**Expected behavior:**

I would expect a TypeAhead using the `animals` as part of the resource list. It shouldn't throw when types are valid.

**Actual behavior:**

It misidentifies the types.

`animals` is treated as a `resourceWrapper`, but `animals` === `resourceWrapper`

![image](https://user-images.githubusercontent.com/331431/79624501-c8e48e80-80d6-11ea-915a-68c65e9e8915.png)

**Comment by matt-gadd** [comment]
I believe your usage is wrong, but the typings are also incorrect (allowing this to happen)
