### ISSUE TITLE
Theme variant class not available immediately after setting theme

### ISSUE THREAD

**Issue by tomdye** [dojo/framework#758]
**Bug** 

Package Version: current

**Code**

```ts
if (!theme.get()) {
	theme.set(materialTheme, 'dark');
}
const variantClass = theme.variant();
// variantClass is undefined
```

**Expected behavior:**

The variant class should be available immediately

**Actual behavior:**

The variant class is undefined.

**Proposed Solution**
The theme middleware should get the theme payload from the them injector rather than relying on the diffProperty function to put it in properties as in the immediate scenario, it has not yet been ran.

**Comment by agubler** [comment]
I believe this is more of conceptual issue that comes about by returning the global theme as the property value and leads to more potential bugs than this narrow issue suggests.

For example this issue also affects calling `theme.classes` after a theme has been set, as that API also leverages the `properties().theme` value internally, meaning that when a set occurs within a widget it will not return the correct classes (similar problem to the variant).

Another rare but inconsistent behaviour, is there is a global theme that is already set and is passed to the widget as the property, if the consumer passes the theme down (as if the best practice to enable users to pass a custom theme), but within the widget they set the global theme using `theme.set` then the user will pass down the "old" global theme by using the property theme value.

Returning the "global" theme as the widget's property is conflating the two distinctly different values that they represent. As a result it feels like the most consistent change would be to stop returning the globally set theme as a widget's property.
