### ISSUE TITLE
Resource transforms are not type safe, and cannot be optional

### ISSUE THREAD

**Issue by matt-gadd** [dojo/framework#763]
**Enhancement**

The current resource and data middleware, makes the `transform` property required regardless of whether the data structure of the resource matches it. Having to import a default transformer for this or implement is tiresome. For example this is the default scenario for a Typeahead in `@dojo/widgets`:

```tsx
import { createResource } from '@dojo/framework/core/resource';
import Typeahead from '@dojo/widgets/typeahead';

const resource = createResource();

const options = [
	{ value: 'cat', label: 'Cat' },
	{ value: 'dog', label: 'Dog' },
	{ value: 'fish', label: 'Fish' }
];

<Typeahead resource={resource(options)} transform={defaultTransform} />
```

On top of this the current transformer is not properly type safe, as it only confirms the keys map to equivalent keys on the data middleware type not the type itself.

To make this type correctly (and optionally when needed only) some changes will have to be made to the resource and data middleware.

**Comment by maier49** [comment]
Fixed in resources rewrite #778
