### ISSUE TITLE
Require resources data to contain a unique ID.

### ISSUE THREAD

**Issue by tomdye** [dojo/framework#849]
**Enhancement** 

In order to ensure that there is always a unique identifier for each item within a resource each item should have a unique id.

**Comment by samends** [comment]
Could you give a bit more information on this? Guessing this issue would be for any widgets that use the resource middleware

**Comment by agubler** [comment]
There is some work going on that’s related to this. It’s more extensive but still covers resources generally. Once it’s raised I’ll link it to this issue
