### ISSUE TITLE
Bug with subtag in i18n middleware

### ISSUE THREAD

**Issue by sebilasse** [dojo/framework#906]
**Bug**
/core/middleware/i18n.ts :
If I have bundles like `'en'` and `'de'` but set a more specific locale, the middleware does nothing.
Assume the above locales with 'en' as the default bundle and

**Code**

`i18n.set({locale: 'de-de'})`

**Expected behavior:**

Switch language to `'de'`

**Actual behavior:**

Nothing happens

**Comment by agubler** [comment]
Hey can you provide a small GitHub example please?

**Comment by sebilasse** [comment]
I hope, codesandbox is fine.
I forked the v6 i18n example (fine) with v7 (bug) …

**Comment by agubler** [comment]
@sebilasse thanks for the example, we've identified the issue in i18n and will look to raise a fix and back-port for 7 over the next few days. Just a note that the locale needs to be `es-MX` not `es-mx` as it is case sensitive (in cldr)

**Comment by sebilasse** [comment]
Hey @agubler 
thank you !
Personally using 8.0 beta … 

just btw
You can see what I am working on here 
https://github.com/redaktor/widgets-preview/
Currently some examples are a mess, but the exiting part is that every “atom” of the ActivityPub protocol will become a dojo widget (yay) –
It could become very useful if friends write ActivityPub clients :)

**Comment by agubler** [comment]
@sebilasse please can you try `@dojo/framework@8.0.0-beta.7`?

**Comment by sebilasse** [comment]
It worked. Sorry for replying late.

**Comment by agubler** [comment]
Thanks for letting us know @sebilasse
