### ISSUE TITLE
Remove tslib and shims

### ISSUE THREAD

**Issue by odoe** [dojo/framework#916]
**Enhancement** 

Would it be possible to remove use shims and tslib? Seems like extra wrappers around features that are fully supported in browsers today. I've been experimenting with trying to run dojo outside the cli build tooling and this usually ends up being a hurdle. Would be a good goal for a future milestone release.

Package Version: 

**Code**

**Expected behavior:**

**Actual behavior:**

**Comment by matt-gadd** [comment]
I believe this is covered in point 4 of this issue https://github.com/dojo/framework/issues/905 so going to close 👍
