### ISSUE TITLE
Migrating from Dojo2 to Dojo3

### ISSUE THREAD

**Issue by yasikmondal** [dojo/framework#96]
Hi,

We are migrating code from dojo2  to dojo3 and it's working fine in local, but when we are trying to do dockerization we are not able to. Can you please help anyone where I am doing mistake. Below is the docker file commands.

```
FROM node:8
WORKDIR /src
ADD . /src
RUN npm install
RUN npm install -g @dojo/cli
EXPOSE 80
CMD ["dojo", "build", "--mode", "dev", "--serve", "--port", "80"] 
```

**Comment by matt-gadd** [comment]
This is more of a support question than an issue as such so i'm going to close, but we have an example docker usage here: https://github.com/matt-gadd/basic-dojo-docker, hope that helps if not please feel free to direct any questions to discord: https://discordapp.com/invite/M7yRngE 😄.
