### ISSUE TITLE
doc for has are misleading

### ISSUE THREAD

**Issue by denov** [dojo/framework#99]
on https://dojo.io/docs/index.html#doc--dojo__framework__v3_0_0__src__has__README_md it states that 

> has() essentially manages feature flags, returning either a truthy value if the feature is present or a falsey value if the feature isn't present. 

but if the feature is not set either via the cli-build-app `-f` flag or via the the `.dojorc` you get the error of `Attempt to detect unregistered has feature "${feature}`.   

from the way the docs ready I would expect `has` to return false when the feature isn't set all at.

**Comment by matt-gadd** [comment]
although we could do with being more explicit, the english above is actually correct. what it means by "feature" is the result of the registered "feature", not that the "feature" hasn't been registered at all.

**Comment by denov** [comment]
lol, you should write what you mean then :)  it doesn't say anything on that page about registering.   if you're reading this for the first time it's not clear what the difference is between not registered and not set.  

the first example code doesn't run without setting other stuff that's not on this page.
